---
title: "annimated map"
author: "Connor Flynn"
date: "9/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(shiny)
library(leaflet)
library(RColorBrewer)
library(xts)
library(rgdal)
library(here)
library(tidyverse)
library(dplyr)
library(lubridate)
```

```{r}
#helper function for choropleth animation
setShapeStyle <- function( map, data = getMapData(map), layerId,
                           stroke = NULL, color = NULL,
                           weight = NULL, opacity = NULL,
                           fill = NULL, fillColor = NULL,
                           fillOpacity = NULL, dashArray = NULL,
                           smoothFactor = NULL, noClip = NULL, label = NULL,
                           options = NULL){
  
  options <- c(list(layerId = layerId),
               options,
               filterNULL(list(stroke = stroke, color = color,
                               weight = weight, opacity = opacity,
                               fill = fill, fillColor = fillColor,
                               fillOpacity = fillOpacity, dashArray = dashArray,
                               smoothFactor = smoothFactor, noClip = noClip, label = label
               )))

  options <- evalFormula(options, data = data)
  options <- do.call(data.frame, c(options, list(stringsAsFactors=FALSE)))
  
  layerId <- options[[1]]
  style <- options[-1]
  if("label" %in% colnames(style)){
    labelData = style[,"label", FALSE]
    style = style[,-which(colnames(style)=="label"), FALSE]
    leaflet::invokeMethod(map, data, "setLabel", "shape", layerId, label)
  }
  leaflet::invokeMethod(map, data, "setStyle", "shape", layerId, style);
}
```



```{r}
#helper function in JS for choropleth animation
leafletjs <-  tags$head(
  tags$script(HTML('
  
window.LeafletWidget.methods.setStyle = function(category, layerId, style){
  var map = this;
  if (!layerId){
    return;
  } else if (!(typeof(layerId) === "object" && layerId.length)){
    layerId = [layerId];
  }
  style = HTMLWidgets.dataframeToD3(style);
  layerId.forEach(function(d,i){
    var layer = map.layerManager.getLayer(category, d);
    if (layer){
      layer.setStyle(style[i]);
    }
  });
};
window.LeafletWidget.methods.setLabel = function(category, layerId, label){
  var map = this;
  if (!layerId){
    return;
  } else if (!(typeof(layerId) === "object" && layerId.length)){
    layerId = [layerId];
  }
  layerId.forEach(function(d,i){
    var layer = map.layerManager.getLayer(category, d);
    if (layer){
      layer.unbindTooltip();
      layer.bindTooltip(label[i])
    }
  });
};
'
  ))
)
```


```{r}
#you only have to do this once!
#download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip" , destfile="world_shape_file.zip")
#system("unzip world_shape_file.zip")

#load spatial data
world_spdf <- readOGR( 
  dsn = "~/Documents/CUH/genes/genes/data/TM_WORLD_BORDERS_SIMPL-0.3" , 
  layer = "TM_WORLD_BORDERS_SIMPL-0.3",
  verbose = FALSE
)
```



```{r}
# insert paper data

paper_data <- read_csv(here("data/pubmed_paper_data_gene2pubmed_simplified.csv"))
```



```{r}
paper_data_country <- paper_data %>% 
  group_by(pubdate) %>% 
  count(country)
```


```{r}
paper_data_country$pubdate <- lubridate::ymd(paper_data_country$pubdate, truncated = 2L)
```

```{r}
country_codes <- read_csv(here("data/country_codes.csv"))
```






```{r}
colnames(paper_data_country)[colnames(paper_data_country) == "country"] <- "Country"
```



```{r}
paper_data_country["Country"][paper_data_country["Country"] == "United States"] <- "United States of America"

paper_data_country["Country"][paper_data_country["Country"] == "England"] <- "The United Kingdom"

paper_data_country["Country"][paper_data_country["Country"] == "Russia (Federation)"] <- "Russian Federation"
  

paper_data_country["Country"][paper_data_country["Country"] == "Czech Republic"] <- "Czechia"

paper_data_country["Country"][paper_data_country["Country"] == "China (Republic : 1949- )"] <- "China"


paper_data_country["Country"][paper_data_country["Country"] == "Korea (South)"] <- "Republic of Korea"


paper_data_country["Country"][paper_data_country["Country"] == "Venezuela"] <- "Venezuela (Bolivarian Republic of)"
	

paper_data_country["Country"][paper_data_country["Country"] == "Turkey"] <- "	
Türkiye"
```




```{r}
#test
paper_data_country <- left_join(paper_data_country, country_codes, by = "Country" )
```

```{r}
#test 

```


```{r}
world_spdf_names <- as.data.frame(world_spdf$NAME)
```

```{r}
#colnames(world_spdf_names)[colnames(world_spdf_names) == "world_spdf$NAME"] <- "NAME"
```



```{r}
#countries_merged <- left_join(paper_data_country, world_spdf_names, by = "NAME")
```

```{r}
selectedData <- paper_data_country[paper_data_country$pubdate == "2002-01-01", ]
```


```{r}
world_spdf$publications <- selectedData$n[match(world_spdf$ISO2, selectedData$Country_code)]
```

```{r}
#create label texts
world_spdf@data$LabelText <- paste0(
  "<b>Country:</b> ", world_spdf@data$NAME,"<br>", 
  "<b>Publications:</b> ", format(world_spdf@data$publications, nsmall=0, big.mark=","))

#define colorpalette for chart legend
paletteBins <- c(0, 1, 50, 100, 1000, 5000, 10000, 20000, 40000)
colorPalette <- colorBin(palette = "YlOrBr", domain = paper_data_country$n, na.color = "transparent", bins = paletteBins)

```

```{r}
#shiny UI
ui <- fluidPage(
                leafletjs,
                titlePanel("Gene Publications"),
                 
                sidebarPanel(width = 2,
                             
                             radioButtons(inputId = "mapType",
                                          label = "Select Map Type",
                                          choices = c("Markers", "Choropleth"),
                                          selected = "Markers",
                                          inline = TRUE),
                             
                             radioButtons(inputId = "frequency",
                                          label = "Select Data Frequency",
                                          choices = c("years"),
                                          selected = "years",
                                          inline = TRUE
                                          ),

                             uiOutput("dateUI")
                             
                             ),

                mainPanel(width = 10,
                          
                          leafletOutput("map", width = "70%", height = "750px")
                          
                          )
                )
```


```{r}
#shiny server
#shiny server
server <- function(input, output, session) {
  
  #create slider input depending on data frequency
  observe({

    allDates <- unique(paper_data_country$pubdate)
    eligibleDates <- allDates[xts::endpoints(allDates, on = input$frequency)]
    
    if(input$frequency == "year"){
      stepSize = 1
    }else{
      stepSize = 1
    }
    
    output$dateUI <- renderUI({
      sliderInput("dateSel", "Date",
                  min = min(eligibleDates),
                  max = max(eligibleDates),
                  value = min(eligibleDates),
                  step = stepSize,
                  timeFormat = "%y, %m, %d",
                  animate = animationOptions(interval = 500, loop = FALSE)
      )
    })
  })

  #filter data depending on selected date
  filteredData <- reactive({
    req(input$dateSel)
    paper_data_country[paper_data_country$pubdate == input$dateSel, ]
  })
  
  #create the base leaflet map
  output$map <- renderLeaflet({
    
    leaflet(world_spdf) %>% 
      addTiles()  %>% 
      setView(lat = 0, lng = 0, zoom = 2) %>%
      
      addPolygons( 
        layerId = ~ISO2,
        fillColor = "lightgray", 
        stroke = TRUE, 
        fillOpacity = 1, 
        color = "white", 
        weight = 1
      ) %>%
      
      #need to specify the leaflet::addLegend function here to avoid ambiguity with the xts::addLegend function
      leaflet::addLegend(pal = colorPalette, values = paper_data_country$n, opacity = 0.9, title = "Publications", position = "bottomleft")
    
  })
  
  
  #prepare data depending on selected date and draw either markers or update polygons depending on the selected map type
  observe({
    
    world_spdf$publications <- filteredData()$n[match(world_spdf$ISO2, filteredData()$Country_code)]
    
    world_spdf@data$LabelText <- paste0(
      "<b>Country:</b> ", world_spdf@data$NAME,"<br>", 
      "<b>Publications:</b> ", format(world_spdf@data$publications, nsmall=0, big.mark=","))

    if(input$mapType == "Markers"){
      
      leafletProxy("map", data = world_spdf) %>%
        clearMarkers() %>%
        setShapeStyle(layerId = ~ISO2, fillColor = "lightgray") %>%
        addCircleMarkers(lng = ~LON,
                         lat = ~LAT,
                         radius = ~log(publications) * 2,
                         weight = 1,
                         opacity = 1,
                         color = ~ifelse(publications > 0, "black", "transparent"),
                         fillColor = ~ifelse(publications > 0, colorPalette(publications), "transparent"),
                         fillOpacity = 0.8,
                         label = ~lapply(LabelText, htmltools::HTML))
      
    }else if(input$mapType == "Choropleth"){
      
      leafletProxy("map", data = world_spdf) %>%
        clearMarkers() %>%
        setShapeStyle(layerId = ~ISO2, fillColor = ~ifelse(publications > 0, colorPalette(publications), "lightgray"), label = world_spdf$LabelText)
      
    }
  })
}

shinyApp(ui, server)  
```

